# Generated by Django 3.2.6 on 2021-08-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safepass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadacademica',
            name='aforo',
            field=models.IntegerField(null=True),
        ),
    ]
