# Generated by Django 3.2.6 on 2021-08-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safepass', '0002_actividadacademica_aforo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
        migrations.AlterField(
            model_name='antecedentespersonales',
            name='rut',
            field=models.CharField(max_length=30, verbose_name='RUT'),
        ),
    ]
