# Generated by Django 3.2.6 on 2021-08-14 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('safepass', '0004_auto_20210812_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_in_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_visita', models.CharField(max_length=30, verbose_name='RUT')),
                ('tipo_de_movimiento', models.CharField(max_length=30, verbose_name='tipo de movimiento')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now, verbose_name='hora')),
            ],
            options={
                'verbose_name': 'Register_in_out',
                'verbose_name_plural': 'Register_in_outs',
            },
        ),
    ]
