# Generated by Django 3.2.6 on 2021-08-14 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safepass', '0005_register_in_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_in_out',
            old_name='rut_visita',
            new_name='rut',
        ),
    ]
