# Generated by Django 3.2.6 on 2021-08-14 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safepass', '0006_rename_rut_visita_register_in_out_rut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register_in_out',
            options={'verbose_name': 'Registro entradas y salidas', 'verbose_name_plural': 'Registro entradas y salidas'},
        ),
    ]
