# Generated by Django 3.2.6 on 2021-08-07 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_general', models.ForeignKey(help_text='Eventos.', on_delete=django.db.models.deletion.CASCADE, to='core.actividadgeneral', verbose_name='actividades general')),
                ('antecedente_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.antecedentespersonales', verbose_name='antecedentes personales')),
                ('antecedente_sanitario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.antecedentessanitarios', verbose_name='antecedentes sanitarios')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
            },
        ),
    ]
